import { useState } from "react";

export default function Quotes(){
    const [quoteText, setQuoteText]=useState(null);
    const affirmations=[
    "You are enough.",
    "Keep going, you’re doing great!",
    "Progress, not perfection.",
    "Every step forward matters.",
    "You have the power to create change.",
    "You are enough just as you are.",
    "Every step you take moves you forward.",
    "You are capable of amazing things.",
    "Your potential is limitless.",
    "You are stronger than you think.",
    "You bring value to the world.",
    "Your hard work is paying off.",
    "You deserve happiness and peace.",
    "You are proud of how far you’ve come.",
    "You are worthy of love and kindness.",
    "Your presence makes a difference.",
    "You learn and grow every day.",
    "You have the power to create change.",
    "Your voice matters.",
    "You radiate positivity and strength.",
    "You are resilient and adaptable.",
    "You choose progress over perfection.",
    "Your dreams are valid and achievable.",
    "You attract good things into your life.",
    "You are confident and courageous.",
    "Your future is full of possibility.",
    "You believe in yourself fully.",
    "You are grateful for today.",
    "You are calm, centered, and focused.",
    "You trust the journey you are on.",
    "You let go of what no longer serves you.",
    "You are at peace with your past.",
    "You embrace challenges as opportunities.",
    "You are creative and resourceful.",
    "You inspire others with your energy.",
    "You are worthy of rest and renewal.",
    "You forgive yourself and move forward.",
    "You are mindful and present in each moment.",
    "You spread kindness wherever you go.",
    "You are always learning and improving.",
    "You deserve success and abundance.",
    "You have everything you need within you.",
    "You are open to new experiences.",
    "You honor your body and mind.",
    "You are proud of your efforts.",
    "You face difficulties with grace.",
    "You are surrounded by love and support.",
    "You are confident in your decisions.",
    "You are creating the life you want.",
    "You trust yourself to handle whatever comes.",
    "You choose joy every day.",
    "You are a source of light to others.",
    "You believe in your own worth.",
    "You are free to be your authentic self.",
    "You are exactly where you need to be.",
     "You are enough",
    "You are going to seize the day",
    "Breathe, you can do this",
    "You are powerful",
    "You are getting better every day",
    "All you need is within you",
    "You are an unstoppable force of nature",
    "You can rise above the thoughts that make you angry or afraid",
    "Today will be a wonderful day",
    "You an achieve anything you strive for",
    "You can do this",
    "You are not governed by your problems",
    "You are led by your ambitions",
    "You will focus on what you can achieve",
    "Each and every day you are moving closer to achieving your goals",
    "You are intelligent and focused",
    "The obstacles in your life help you to evolve and grow",
    "Nothing is insurmountable",
    "You can be whoever you want to be",
    "You are not defined by your past, you are driven by your future",
    "Today will be a productive day",
    "You desere the space you occupy",
    "You are constantly growing and evolving into a better person",
    "Allow yourself to accept you for who you are",
    "You deserve to forgive and be forgiven",
    "You have survived difficult times before this, you will get through this as well",
    "Others care about you and your well-being",
    "You are loved",
    "Your intrusive thoughts do not speak for reality",
    "You are doing your best",
    "Your difficult times do not define you",
    "You belong in this world",
    "Your life has meaning",
    "Your mistakes do not define you",
    "To love oneself is the beginning of a lifelong romance",
    "I am worthy of love and kindness.",
    "Today I choose peace over worry.",
    "I am enough just as I am.",
    "I am proud of my progress.",
    "I embrace my uniqueness.",
    "I trust myself to grow every day.",
    "My potential is limitless.",
    "I am grateful for this moment.",
    "I radiate positivity and light.",
    "I believe in my ability to succeed.",
    "I am becoming the best version of myself.",
    "I release all doubt and welcome confidence.",
    "I am proud of how far I’ve come.",
    "I choose to focus on what I can control.",
    "I attract opportunities that align with my purpose.",
    "I am resilient, strong, and brave.",
    "My presence makes a positive impact.",
    "I let go of negative thoughts and embrace joy.",
    "I am open to new adventures.",
    "My mind is clear and focused.",
    "I honor my progress, no matter how small.",
    "I deserve happiness and abundance.",
    "I choose self-compassion over criticism.",
    "I trust the journey of my life.",
    "I am grateful for the lessons I’ve learned.",
    "I welcome love, success, and joy into my life.",
    "My energy is calm and balanced.",
    "I embrace change as growth.",
    "I believe in myself and my dreams.",
    "I am surrounded by support and love.",
    "I am in charge of my thoughts and emotions.",
    "I am a magnet for positivity.",
    "I let go of fear and step into courage.",
    "My life is filled with blessings.",
    "I am capable of creating the life I want.",
    "I forgive myself and move forward with grace.",
    "I trust that everything is unfolding perfectly.",
    "I deserve rest, joy, and peace.",
    "I am patient with myself and others.",
    "I choose progress over perfection.",
    "I radiate confidence and inner strength.",
    "I am thankful for my body and health.",
    "I create space for happiness in my life.",
    "I focus on what matters most to me.",
    "I choose hope over doubt.",
    "I am becoming stronger each day.",
    "I attract peace, love, and abundance.",
    "I am proud of my efforts.",
    "I trust that I am on the right path.",
    "I am enough just as I am.",
    "I see challenges as opportunities to grow.",
    "I let go of what I cannot change.",
    "I am worthy of success and joy.",
    "I choose kindness every day.",
    "I am grateful for the gift of today.",
    "My life is full of endless possibilities.",
    "I deserve love and give love freely.",
    "I am courageous in the face of challenges.",
    "I attract positive energy everywhere I go.",
    "I am open to learning and growing.",
    "I trust my inner wisdom.",
    "I release comparison and embrace my uniqueness.",
    "I am grounded, calm, and secure.",
    "I am a source of inspiration to others.",
    "I radiate gratitude and joy.",
    "I trust the timing of my life.",
    "I am aligned with my purpose.",
    "I am free to create my own happiness.",
    "I have the power to overcome obstacles.",
    "I am proud of who I am becoming.",
    "I attract abundance and prosperity.",
    "I am a light in the world.",
    "I welcome peace into my life.",
    "I am stronger than my fears.",
    "I honor my needs and boundaries.",
    "I let go of self-doubt and step into confidence.",
    "I am a work in progress, and that is okay.",
    "I celebrate my small wins.",
    "I choose joy in the present moment.",
    "I am capable of amazing things.",
    "I am surrounded by abundance.",
    "I release stress and invite calm.",
    "I deserve to take up space.",
    "I am grateful for new beginnings.",
    "I radiate self-love and compassion.",
    "I welcome new opportunities with excitement.",
    "I am open to receiving love and kindness.",
    "I am resilient and adaptable.",
    "I trust my ability to handle challenges.",
    "I am proud of the progress I’ve made.",
    "I choose to be kind to myself today.",
    "I am worthy of respect and love.",
    "I release worry and trust the process.",
    "I am grateful for the beauty in my life.",
    "I attract opportunities for growth.",
    "I choose to focus on what brings me joy.",
    "I am learning to trust myself fully.",
    "I am enough, exactly as I am.",
    "I honor my strengths and talents.",
    "I am grateful for my unique journey.",
    "I release the past and embrace the present.",
    "I am constantly evolving into my best self.",
    "I trust myself to make good choices.",
    "I am open to receiving guidance.",
    "I choose gratitude every day.",
    "I deserve love, happiness, and peace.",
    "I let go of fear and step into love.",
    "I am worthy of my dreams.",
    "I am learning to be at peace with myself.",
    "I am grateful for the gift of life.",
    "I trust the universe to guide me.",
    "I radiate love, joy, and positivity.",
    "I am strong, capable, and worthy.",
    "I choose faith over fear.",
    "I am proud of my uniqueness.",
    "I create space for healing and growth.",
    "I trust myself to handle life’s challenges.",
    "I welcome abundance into my life.",
    "I let go of what no longer serves me.",
    "I am resilient, resourceful, and strong.",
    "I am grateful for the support around me.",
    "I embrace each day with gratitude.",
    "I am confident in my abilities.",
    "I choose to see the good in every situation.",
    "I am growing into the best version of me.",
    "I am worthy of my goals.",
    "I radiate positivity and attract good things.",
    "I am enough, always.",
    "I am grateful for my journey so far.",
    "I let go of negativity and embrace joy.",
    "I believe in myself and my abilities.",
    "I am deserving of peace and rest.",
    "I attract success and happiness.",
    "I choose self-love every day.",
    "I am grateful for the little things in life.",
    "I am strong and capable of change.",
    "I welcome joy and love into my heart.",
    "I am proud of all I have accomplished.",
    "I choose to focus on the present.",
    "I am a magnet for positivity and love.",
    "I am worthy of compassion and care.",
    "I let go of fear and embrace confidence.",
    "I trust the journey I am on.",
    "I deserve to live a life I love.",
    "I am patient with my growth.",
    "I attract love, joy, and abundance.",
    "I am thankful for today.",
    "I am confident and courageous.",
    "I radiate peace and calm.",
    "I am grateful for who I am.",
    "I am becoming more mindful each day.",
    "I am capable of overcoming difficulties.",
    "I choose to live with gratitude.",
    "I am worthy of kindness and love.",
    "I trust myself to find the way.",
    "I am grateful for the present moment.",
    "I attract opportunities for happiness.",
    "I am proud of my progress and growth.",
    "I am enough just as I am.",
    "I am resilient in the face of change.",
    "I choose joy every day.",
    "I am open to endless possibilities.",
    "I deserve success and peace.",
    "I radiate love and compassion.",
    "I trust my path and embrace it fully.",
    "I am worthy of everything good.",
    "I am grateful for today’s opportunities.",
    "I choose to be kind to myself.",
    "I am confident in who I am.",
    "I attract positivity and joy.",
    "I am enough and always have been.",
    "I welcome abundance into every part of my life.",
    "I am learning to embrace my uniqueness.",
    "I choose hope and faith every day.",
    "I am capable of achieving my dreams.",
    "I let go of self-doubt and choose confidence.",
    "I am grateful for my growth.",
    "I am becoming stronger each day.",
    "I choose peace in my heart.",
    "I am a light for those around me.",
    "I trust that everything will be okay.",
    "I am grateful for my journey.",
    "I am proud of my progress.",
    "I deserve to rest and recharge.",
    "I radiate happiness and gratitude.",
    "I am open to new experiences.",
    "I let go of the past and embrace now.",
    "I trust myself completely.",
    "I am grateful for this life.",
    "I deserve love and abundance.",
    "I am open to receiving blessings.",
    "I am confident in my choices.",
    "I radiate positivity and hope.",
    "I am grateful for small joys.",
    "I choose to love myself deeply.",
    "I am open to endless growth.",
    "I trust the universe’s plan for me.",
    "I am worthy of all good things.",
    "I let go of negativity and choose peace.",
    "I am resilient and full of strength.",
    "I am enough every single day.",
    "I am grateful for love and kindness.",
    "I choose joy and peace now.",
    "I am deserving of happiness.",
    "I radiate gratitude and confidence.",
    "I am open to abundance today.",
    "I am thankful for who I am becoming.",
    "I believe in myself always.",
    "I am grateful for opportunities to grow.",
    "I am calm, confident, and strong.",
    "I deserve rest, love, and peace.",
    "I am worthy of respect and kindness.",
    "I let go of fear and choose courage.",
    "I am grateful for new opportunities.",
    "I am enough in this very moment.",
    "I radiate love and joy.",
    "I am open to receiving positivity.",
    "I choose peace and serenity now.",
    "I am worthy of my dreams and goals.",
    "I am thankful for today’s lessons.",
    "I trust myself to move forward.",
    "I am proud of my unique journey.",
    "I deserve kindness and compassion.",
    "I am grateful for my resilience.",
    "I attract good things every day.",
    "I am becoming my best self.",
    "I am enough, just as I am.",
    "I trust that better days are coming.",
    "I am open to new adventures.",
    "I radiate calmness and positivity.",
    "I am worthy of joy and peace.",
    "I am grateful for the love in my life.",
    "I choose to see beauty in everything.",
    "I am confident and full of hope.",
    "I am proud of who I am.",
    "I attract abundance every day.",
    "I let go of doubt and step into faith.",
    "I am grateful for life’s blessings.",
    "I am worthy of success and happiness.",
    "I am enough, always and forever.",
    "I radiate gratitude and peace.",
    "I am open to joy in all forms.",
    "I am thankful for my journey.",
    "I choose love over fear.",
    "I am becoming more mindful daily.",
    "I am deserving of everything good.",
    "I am grateful for the present moment.",
    "I am strong, hopeful, and kind.",
    "I let go of worry and embrace calm.",
    "I am open to possibilities.",
    "I am enough and always will be.",
    "I am grateful for my progress.",
    "I choose peace and gratitude today.",
    "I am proud of how far I’ve come.",
    "I deserve all the good things life offers.",
    "I radiate hope and joy.",
    "I am worthy of love and respect.",
    "I am grateful for this day.",
    "I am enough and always have been."
  ];
 
    async function quote(){
        let ran=Math.random()*(affirmations.length-1);
        setQuoteText(affirmations[Math.round(ran)]);
    }
    return(
    <>
    <div className="affirmationsApp">
        <button onClick={quote}>Get affirmation</button>
        <div>{quoteText}</div>
    </div>
    
    </>
    );
}